### ISSUE TITLE
Change HydroShare open with CUAHSI JupyterHub behavior to open in lab view

### ISSUE THREAD

**Issue by aaraney** [CUAHSI/jupyterhub#2]
[This HydroShare resource](https://www.hydroshare.org/resource/33c45575b95f45c4bf7335faab67ed36/) defines the "open with" behavior that allows a user to open a HydroShare resource in CUAHSI JupyterHub. The functionality is provided by a JupyterLab server plugin, [`nbfetch`](https://github.com/hydroshare/nbfetch). The default behavior or `nbfetch` is to open in jupyter's "tree" view. However, this can be changed by passing the query parameter pair, `app=lab` (see [src](https://github.com/hydroshare/nbfetch/blob/cbc90aadf12a1648d76358b2d474f16be9b275f1/nbfetch/handlers.py#L247)). 

@Castronova and I agree the default behavior should be to open in "lab" view. This issue tracks that effort and related discussion.

**Comment by Castronova** [comment]
This will partially resolve issue #4 since we'll no longer be rendering the `tree` view.

**Comment by Castronova** [comment]
Modified the app_launch url in the [web connector](https://www.hydroshare.org/resource/33c45575b95f45c4bf7335faab67ed36/) to ` https://jupyterhub.cuahsi.org/hub/spawn?next=/user-redirect/hs-pull?id=${HS_RES_ID}%26app%3Dlab`

**Comment by Castronova** [comment]
According to @sblack-usu the `next` portion of the URL needs to be encoded for it to be interpreted correctly. For example,

`https://jupyterhub.cuahsi.org/hub/spawn?next=/user-redirect/hs-pull?id%3D%24%7BHS_RES_ID%7D%26app%3Dlab`
