### ISSUE TITLE
Register A-record for JupyterHub Development Cluster

### ISSUE THREAD

**Issue by Castronova** [CUAHSI/jupyterhub#5]
A JupyterHub development cluster has been deployed at 34.122.235.106 for testing software upgrades,  bugs, and enhancements for the community jupyterhub platform. 
 This system needs an a-record on the *.cuahsi.org domain to enable and test SSL. 

## Action

Create an a-record for the following:

| url | ip address |
|---|---|
|dev-jupyterhub.cuahsi.org |34.122.235.106|

**Comment by Castronova** [comment]
@martinseul tagging you so you're aware of this ticket.

**Comment by martinseul** [comment]
@Castronova A record was crated please let me know if you see any issues.

**Comment by Castronova** [comment]
Thanks @martinseul
